### PR TITLE
Add APNG support + partial clean-up

### PR DESCRIPTION
**Pull request by FredHappyface**
This pull request adds APNG support, adds a bit of documentation (though this is still WIP) and some cleanup

### CODE REVIEW

**Comment by FredHappyface** [comment]
I also noted significant performance issues with animating stickers in the keyboard so have disabled these animation to dramatically improve performance (30% to about 2% on a Nokia 8 Sirocco)

**Comment by rzhou1999** [comment]
Appreciate the PR as always-- I see no issues with APNG support, but I'm perhaps a little hesitant to disable animation wholesale (I sort of modeled this app after sticker implementations in gboard, wechat, signal, etc. and they usually have animated icons). What performance metrics are you using for this/how many animated stickers do you use? I have around 40+ gifs per directory and I haven't really seen much in terms of memory/battery usage. Maybe as a toggle?

**Comment by FredHappyface** [comment]
I was using the Android profiler. The stickers animate once sent but don't animate in gboard with usticker either. Still I have no issue adding this as a toggle but think it should be disabled by default as it was using 2x the resources of every other app in my system. Can drop a screenshot if you would find that helpful?

**Comment by FredHappyface** [comment]
With glide-animation 

image


Without 

image


Considering that this is a 2 year old high end device I wouldn't expect a sticker board to use such a significant amount of CPU 

In this second test gifs were running fine so it seems to be some issue with glide and webp 

I'll look at adding a toggle to enable glide animations (webp and apng)

**Comment by FredHappyface** [comment]
I've added said toggle for those that want/ need it

I've also added a bit of padding to the widgets in the main activity as I was finding that I was mis-tapping a lot - hope that's ok

Thanks for the review and I hope these changes address the issues raised

**Comment by FredHappyface** [comment]
Using android P+ features rather than glide/ gif lib seems to improve render cpu usage:

image

It's around half that of glide use for webp and gif

**Comment by rzhou1999** [comment]
Semester is over and education is graduated, so I can finally get back to clearing some of these PRs and issues. LGTM-- thanks as always~

**Pull request merged**
